### ISSUE TITLE
T

### ISSUE THREAD

**Issue by tingel1** [ReactiveMarkets/NLog.Targets.ElasticSearch#16]
Case sensitiv? 

In my nlog config: field name="Exception" layout="${exception:format=tostring}" 

 I log in my App -> _log.Error(actionExecutedContext.Exception);

Exception on: var result = _client.Bulk<byte[]>(payload);

with: Non system type -> "Newtonsoft.Json.JsonReaderException"

Because:

 field.Name = "Exception"  
and
 document.Add("exception", logEvent.Exception); = "exception"

Nlog write both fields and elastic search throws a execption because he cant log real exception objects. 

lg Jörg

**Comment by markmcdowell** [comment]
Could you post what your nlog config for this target is. Exception objects should be fine.

Thanks, Mark




On Thu, Apr 7, 2016 at 12:25 AM -0700, "tingel1" <notifications@github.com> wrote:












Case sensitiv? 



In my nlog config: 



I log in my App -> _log.Error(actionExecutedContext.Exception);



Exception on: var result = _client.Bulk(payload);



with: Non system type -> "Newtonsoft.Json.JsonReaderException"



Because:



field.Name = "Exception"


and

 document.Add("exception", logEvent.Exception); = "exception"



Nlog write both fields and elastic search throws a execption because he cant log real exception objects. 



lg Jörg

**Comment by markmcdowell** [comment]
Fixed by #22
